---
id: data-science-rb
base_name: ruby-with-apache-arrow-joins-data-processing-languages
tags:
- rabbit
- ruby
- arrow
- data
presentation_date: 2017-05-19
version: 2017.5.19.0
licenses:
- CC-BY-SA-4.0
slideshare_id: datasciencerb
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: 
  speaker_deck_user: 
